import { ChangeDetectionStrategy, Component, DestroyRef, inject, signal } from '@angular/core';
import { takeUntilDestroyed, toObservable, toSignal } from '@angular/core/rxjs-interop';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { ActivatedRoute, RouterLink, RouterLinkActive } from '@angular/router';
import { combineLatest, map, of, switchMap } from 'rxjs';
import { AdminApiService, ProductApiService } from '../../core/api.services';

interface AdminRow { id: string; primary: string; secondary: string; detail: string; status: string; raw?: unknown; }

@Component({
  standalone: true,
  imports: [RouterLink, RouterLinkActive, MatButtonModule, MatIconModule],
  template: `<section class="admin-shell"><aside class="admin-nav"><div><span>FM</span><strong>Operations</strong></div><a routerLink="/admin" [routerLinkActiveOptions]="{exact:true}" routerLinkActive="active"><mat-icon>dashboard</mat-icon>Dashboard</a><a routerLink="/admin/products" routerLinkActive="active"><mat-icon>inventory_2</mat-icon>Products</a><a routerLink="/admin/categories" routerLinkActive="active"><mat-icon>category</mat-icon>Categories</a><a routerLink="/admin/inventory" routerLinkActive="active"><mat-icon>warehouse</mat-icon>Inventory</a><a routerLink="/admin/orders" routerLinkActive="active"><mat-icon>local_shipping</mat-icon>Orders</a><a routerLink="/admin/users" routerLinkActive="active"><mat-icon>group</mat-icon>Users</a></aside><main class="content"><header><div><span class="eyebrow">ForgeMart operations</span><h1>{{ title() }}</h1><p>{{ subtitle() }}</p></div><button mat-flat-button (click)="refresh.update(value=>value+1)"><mat-icon>refresh</mat-icon>Refresh</button></header><div class="table fm-panel"><div class="table-head"><span>Name / reference</span><span>Details</span><span>Status</span><span>Action</span></div>@if(rows();as data){@for(row of data;track row.id){<article><div><strong>{{ row.primary }}</strong><small>{{ row.secondary }}</small></div><span>{{ row.detail }}</span><span class="status-chip" [class.out]="row.status==='Inactive'||row.status==='Out of stock'||row.status==='Cancelled'">{{ row.status }}</span><div>@if(section()==='inventory'){<button mat-stroked-button (click)="restock(row.id)">+10 restock</button>}@else if(section()==='orders'&&nextStatus(row.status)){<button mat-stroked-button (click)="advance(row.id,row.status)">→ {{ nextStatus(row.status) }}</button>}@else{<button mat-button disabled>Inspect</button>}</div></article>}@empty{<div class="empty-state">No records found.</div>}}@else{<div class="loading-state">Loading {{ section() }}…</div>}</div></main></section>`,
  styles: [`.admin-shell{display:grid;grid-template-columns:240px 1fr;min-height:calc(100vh - 74px)}.admin-nav{display:flex;flex-direction:column;gap:7px;padding:28px 18px;color:#c7d0d5;background:#202a31}.admin-nav>div{display:flex;align-items:center;gap:10px;margin:0 8px 24px;color:white}.admin-nav>div span{display:grid;place-items:center;width:38px;height:38px;border-radius:8px;background:var(--fm-orange);font-weight:900}.admin-nav a{display:flex;align-items:center;gap:12px;padding:11px 13px;border-radius:8px;font-size:.85rem;font-weight:700}.admin-nav a:hover,.admin-nav a.active{color:white;background:#34434c}.admin-nav mat-icon{color:#91a0a8}.admin-nav a.active mat-icon{color:#ff8a3d}.content{min-width:0;padding:38px clamp(22px,4vw,58px)}header{display:flex;justify-content:space-between;align-items:end;margin-bottom:28px}header h1{margin:5px 0;font-size:3rem;letter-spacing:-.055em;text-transform:capitalize}header p{margin:0;color:var(--fm-steel)}header button{color:white;background:var(--fm-ink)}.table{overflow:hidden;box-shadow:none}.table-head,article{display:grid;grid-template-columns:minmax(220px,1.2fr) minmax(180px,1fr) 140px 150px;align-items:center;gap:18px;padding:15px 20px}.table-head{color:#9aabb4;background:#26343d;font-size:.7rem;font-weight:800;text-transform:uppercase;letter-spacing:.08em}article{min-height:72px;border-bottom:1px solid var(--fm-line)}article:last-child{border:0}article strong,article small{display:block}article small,article>span:not(.status-chip){margin-top:4px;color:var(--fm-steel);font-size:.75rem}.status-chip{width:max-content}article button{font-size:.72rem}@media(max-width:820px){.admin-shell{grid-template-columns:1fr}.admin-nav{display:none}.content{padding:24px 12px}.table-head{display:none}article{grid-template-columns:1fr auto}article>span:not(.status-chip){grid-column:1}.status-chip{grid-row:1;grid-column:2}article>div:last-child{grid-column:2}}`],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AdminSectionComponent {
  private readonly products=inject(ProductApiService); private readonly admin=inject(AdminApiService); private readonly destroyRef=inject(DestroyRef); readonly refresh=signal(0);
  readonly section=toSignal(inject(ActivatedRoute).paramMap.pipe(map(params=>params.get('section')??'products')),{initialValue:'products'});
  readonly title=()=>({products:'Products',categories:'Categories',inventory:'Inventory',orders:'Orders',users:'Users'}[this.section()]??'Operations');
  readonly subtitle=()=>({products:'Manage the complete active and inactive catalog.',categories:'Keep customer navigation structured and current.',inventory:'Every adjustment creates a traceable stock movement.',orders:'Advance orders only through valid state transitions.',users:'Review customer and administrator access.'}[this.section()]??'ForgeMart administration.');
  readonly rows=toSignal(combineLatest([toObservable(this.section),toObservable(this.refresh)]).pipe(switchMap(([section])=>this.load(section))));
  private load(section:string){
    if(section==='products')return this.products.search({page:1,pageSize:100,includeInactive:true}).pipe(map(result=>result.items.map(item=>({id:item.id,primary:item.name,secondary:item.sku,detail:`${item.brand} · ${this.money(item.currentPrice)}`,status:item.isActive?'Active':'Inactive'}))));
    if(section==='categories')return this.products.categories(true).pipe(map(items=>items.map(item=>({id:item.id,primary:item.name,secondary:`${item.productCount} products`,detail:item.description,status:item.isActive?'Active':'Inactive'}))));
    if(section==='inventory')return this.admin.inventory().pipe(map(items=>items.map(item=>({id:item.productId,primary:item.productName,secondary:item.sku,detail:`${item.quantity} in stock · low at ${item.minimumStockLevel}`,status:item.quantity===0?'Out of stock':item.isLowStock?'Low stock':'Healthy'}))));
    if(section==='orders')return this.admin.orders().pipe(map(result=>result.items.map(item=>({id:item.id,primary:item.orderNumber,secondary:item.customerName,detail:this.money(item.grandTotal),status:item.status}))));
    if(section==='users')return this.admin.users().pipe(map(items=>items.map(item=>({id:String(item['id']),primary:`${item['firstName']} ${item['lastName']}`,secondary:String(item['email']),detail:String(item['role']),status:item['isActive']?'Active':'Inactive'}))));
    return of([] as AdminRow[]);
  }
  restock(id:string):void{this.admin.adjustInventory(id,{quantity:10,type:'Restock',reason:'Admin dashboard restock',increase:true}).pipe(takeUntilDestroyed(this.destroyRef)).subscribe(()=>this.refresh.update(value=>value+1));}
  advance(id:string,status:string):void{const next=this.nextStatus(status);if(next)this.admin.updateOrderStatus(id,next).pipe(takeUntilDestroyed(this.destroyRef)).subscribe(()=>this.refresh.update(value=>value+1));}
  nextStatus(status:string):string|null{return({PendingPayment:'Paid',Paid:'Processing',Processing:'Shipped',Shipped:'Delivered'} as Record<string,string>)[status]??null;}
  money(value:number):string{return new Intl.NumberFormat('sr-RS',{style:'currency',currency:'RSD'}).format(value);}
}
